[project]
name = "static-audiobooks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2==2.11.2",
    "markupsafe==1.1.1",
    "mutagen==1.45.1",
    "pyyaml>=6.0.2",
]
